version: '3.9'

services:
  db:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_DB: plantation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - "9090:9090"
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge